### ISSUE TITLE
dhcp does not answer with correct ClientId

### ISSUE THREAD

**Issue by lynxis** [mirage/charrua#84]
When using `dhcpcd` on archlinux to retrieve an address from the mirage dhcp server. The server does not respond with the correct ClientId.
dhcpc send CliendId with type 0xff,
mirage server answer with CliendId with type 0x00

**Comment by lynxis** [comment]
doesn't work yet. works for me, but for other client id == type 0x0 it's broken.

**Comment by lynxis** [comment]
Fixed by #98

**Comment by hannesm** [comment]
now that #98 is merged, this can be closed.
